package pojos;
// Generated 6 abr. 2022 16:44:48 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autors generated by hbm2java
 */
public class Autors implements java.io.Serializable {

	private int codiAutor;
	private String nom;
	private String pais;
	private String estil;
	private Set<Llibres> llibreses = new HashSet(0);

	public Autors() {
	}

	public Autors(int codiAutor, String nom) {
		this.codiAutor = codiAutor;
		this.nom = nom;
	}

	public Autors(int codiAutor, String nom, String pais, String estil, Set llibreses) {
		this.codiAutor = codiAutor;
		this.nom = nom;
		this.pais = pais;
		this.estil = estil;
		this.llibreses = llibreses;
	}

	public int getCodiAutor() {
		return this.codiAutor;
	}

	public void setCodiAutor(int codiAutor) {
		this.codiAutor = codiAutor;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getEstil() {
		return this.estil;
	}

	public void setEstil(String estil) {
		this.estil = estil;
	}

	public Set<Llibres> getLlibreses() {
		return this.llibreses;
	}

	public void setLlibreses(Set<Llibres> llibreses) {
		this.llibreses = llibreses;
	}

	@Override
	public String toString() {
		return "Autors [codiAutor=" + codiAutor + ", estil=" + estil + ", nom=" + nom + ", pais=" + pais + "]";
	}

}
