package pojos;
// Generated 6 abr. 2022 16:44:48 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Idiomes generated by hbm2java
 */
public class Idiomes implements java.io.Serializable {

	private int codi;
	private String descripcio;
	private Set llibreses = new HashSet(0);

	public Idiomes() {
	}

	public Idiomes(int codi, String descripcio) {
		this.codi = codi;
		this.descripcio = descripcio;
	}

	public Idiomes(int codi, String descripcio, Set llibreses) {
		this.codi = codi;
		this.descripcio = descripcio;
		this.llibreses = llibreses;
	}

	public int getCodi() {
		return this.codi;
	}

	public void setCodi(int codi) {
		this.codi = codi;
	}

	public String getDescripcio() {
		return this.descripcio;
	}

	public void setDescripcio(String descripcio) {
		this.descripcio = descripcio;
	}

	public Set getLlibreses() {
		return this.llibreses;
	}

	public void setLlibreses(Set llibreses) {
		this.llibreses = llibreses;
	}

}
