package pojos;
// Generated 6 abr. 2022 16:44:48 by Hibernate Tools 5.6.3.Final

/**
 * Llibres generated by hbm2java
 */
public class Llibres implements java.io.Serializable {

	private int codiLlibre;
	private Autors autors;
	private Idiomes idiomes;
	private String titol;
	private Integer pagines;

	public Llibres() {
	}

	public Llibres(int codiLlibre, Autors autors, Idiomes idiomes, String titol) {
		this.codiLlibre = codiLlibre;
		this.autors = autors;
		this.idiomes = idiomes;
		this.titol = titol;
	}

	public Llibres(int codiLlibre, Autors autors, Idiomes idiomes, String titol, Integer pagines) {
		this.codiLlibre = codiLlibre;
		this.autors = autors;
		this.idiomes = idiomes;
		this.titol = titol;
		this.pagines = pagines;
	}

	public int getCodiLlibre() {
		return this.codiLlibre;
	}

	public void setCodiLlibre(int codiLlibre) {
		this.codiLlibre = codiLlibre;
	}

	public Autors getAutors() {
		return this.autors;
	}

	public void setAutors(Autors autors) {
		this.autors = autors;
	}

	public Idiomes getIdiomes() {
		return this.idiomes;
	}

	public void setIdiomes(Idiomes idiomes) {
		this.idiomes = idiomes;
	}

	public String getTitol() {
		return this.titol;
	}

	public void setTitol(String titol) {
		this.titol = titol;
	}

	public Integer getPagines() {
		return this.pagines;
	}

	public void setPagines(Integer pagines) {
		this.pagines = pagines;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */

	@Override
	public String toString() {
		return "Llibres [codiLlibre=" + codiLlibre + ", pagines=" + pagines + ", titol=" + titol + "]";
	}

}
