package pojos;
// Generated 21 feb. 2022 17:59:07 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumne generated by hbm2java
 */
public class Alumne implements java.io.Serializable {

	private int nexp;
	private Integer edat;
	private String nom;
	private String tlf;
	private Set<Assignatura> assignaturas = new HashSet<>(0);

	public Alumne() {
	}

	public Alumne(int nexp) {
		this.nexp = nexp;
	}

	public Alumne(int nexp, Integer edat, String nom, String tlf, Set<Assignatura> assignaturas) {
		this.nexp = nexp;
		this.edat = edat;
		this.nom = nom;
		this.tlf = tlf;
		this.assignaturas = assignaturas;
	}

	public int getNexp() {
		return this.nexp;
	}

	public void setNexp(int nexp) {
		this.nexp = nexp;
	}

	public Integer getEdat() {
		return this.edat;
	}

	public void setEdat(Integer edat) {
		this.edat = edat;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Set<Assignatura> getAssignaturas() {
		return this.assignaturas;
	}

	public void setAssignaturas(Set<Assignatura> assignaturas) {
		this.assignaturas = assignaturas;
	}

}
