package pojos;
// Generated 21 feb. 2022 17:59:07 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Empleats generated by hbm2java
 */
public class Empleats implements java.io.Serializable {

	private short empNo;
	private Departaments departaments;
	private String cognoms;
	private String nom;
	private Date dataAlta;
	private Float sou;
	private Float comissio;

	public Empleats() {
	}

	public Empleats(short empNo, Departaments departaments, String cognoms, String nom) {
		this.empNo = empNo;
		this.departaments = departaments;
		this.cognoms = cognoms;
		this.nom = nom;
	}

	public Empleats(short empNo, Departaments departaments, String cognoms, String nom, Date dataAlta, Float sou,
			Float comissio) {
		this.empNo = empNo;
		this.departaments = departaments;
		this.cognoms = cognoms;
		this.nom = nom;
		this.dataAlta = dataAlta;
		this.sou = sou;
		this.comissio = comissio;
	}

	public short getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(short empNo) {
		this.empNo = empNo;
	}

	public Departaments getDepartaments() {
		return this.departaments;
	}

	public void setDepartaments(Departaments departaments) {
		this.departaments = departaments;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDataAlta() {
		return this.dataAlta;
	}

	public void setDataAlta(Date dataAlta) {
		this.dataAlta = dataAlta;
	}

	public Float getSou() {
		return this.sou;
	}

	public void setSou(Float sou) {
		this.sou = sou;
	}

	public Float getComissio() {
		return this.comissio;
	}

	public void setComissio(Float comissio) {
		this.comissio = comissio;
	}

	@Override
	public String toString() {
		return "{" +
				" empNo='" + getEmpNo() + "'" +
				", cognoms='" + getCognoms() + "'" +
				", nom='" + getNom() + "'" +
				", dataAlta='" + getDataAlta() + "'" +
				", sou='" + getSou() + "'" +
				", comissio='" + getComissio() + "'" +
				"}";
	}

}
