package pojos;
// Generated 14 mar. 2022 18:50:50 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Assistencies generated by hbm2java
 */
public class Assistencies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codiAssistencia;
	private Clients clients;
	private Serveis serveis;
	private Usuaris usuaris;
	private Date data;
	private String observacions;

	public Assistencies() {
	}

	public Assistencies(Clients clients, Serveis serveis, Usuaris usuaris, Date data) {
		this.clients = clients;
		this.serveis = serveis;
		this.usuaris = usuaris;
		this.data = data;
	}

	public Assistencies(Clients clients, Serveis serveis, Usuaris usuaris, Date data, String observacions) {
		this.clients = clients;
		this.serveis = serveis;
		this.usuaris = usuaris;
		this.data = data;
		this.observacions = observacions;
	}

	public Integer getCodiAssistencia() {
		return this.codiAssistencia;
	}

	public void setCodiAssistencia(Integer codiAssistencia) {
		this.codiAssistencia = codiAssistencia;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	public Serveis getServeis() {
		return this.serveis;
	}

	public void setServeis(Serveis serveis) {
		this.serveis = serveis;
	}

	public Usuaris getUsuaris() {
		return this.usuaris;
	}

	public void setUsuaris(Usuaris usuaris) {
		this.usuaris = usuaris;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getObservacions() {
		return this.observacions;
	}

	public void setObservacions(String observacions) {
		this.observacions = observacions;
	}

}
