package pojos;
// Generated 14 mar. 2022 18:50:50 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuaris generated by hbm2java
 */
public class Usuaris implements java.io.Serializable {

	private String idUsuari;
	private Perfils perfils;
	private String password;
	private String nom;
	private String cognoms;
	private String correu;
	private Integer numcolegiat;
	private String especialitat;
	private Set<Assistencies> assistencieses = new HashSet<>();

	public Usuaris() {
	}

	public Usuaris(String idUsuari, Perfils perfils, String password, String nom, String cognoms, String correu) {
		this.idUsuari = idUsuari;
		this.perfils = perfils;
		this.password = password;
		this.nom = nom;
		this.cognoms = cognoms;
		this.correu = correu;
	}

	public Usuaris(String idUsuari, Perfils perfils, String password, String nom, String cognoms, String correu,
			Integer numcolegiat, String especialitat, Set<Assistencies> assistencieses) {
		this.idUsuari = idUsuari;
		this.perfils = perfils;
		this.password = password;
		this.nom = nom;
		this.cognoms = cognoms;
		this.correu = correu;
		this.numcolegiat = numcolegiat;
		this.especialitat = especialitat;
		this.assistencieses = assistencieses;
	}

	public String getIdUsuari() {
		return this.idUsuari;
	}

	public void setIdUsuari(String idUsuari) {
		this.idUsuari = idUsuari;
	}

	public Perfils getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Perfils perfils) {
		this.perfils = perfils;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getCorreu() {
		return this.correu;
	}

	public void setCorreu(String correu) {
		this.correu = correu;
	}

	public Integer getNumcolegiat() {
		return this.numcolegiat;
	}

	public void setNumcolegiat(Integer numcolegiat) {
		this.numcolegiat = numcolegiat;
	}

	public String getEspecialitat() {
		return this.especialitat;
	}

	public void setEspecialitat(String especialitat) {
		this.especialitat = especialitat;
	}

	public Set<Assistencies> getAssistencieses() {
		return this.assistencieses;
	}

	public void setAssistencieses(Set<Assistencies> assistencieses) {
		this.assistencieses = assistencieses;
	}
	
	@Override
	public String toString() {
		return "Usuaris [assistencieses=" + assistencieses + ", cognoms=" + cognoms + ", correu=" + correu
				+ ", especialitat=" + especialitat + ", idUsuari=" + idUsuari + ", nom=" + nom + ", numcolegiat="
				+ numcolegiat + ", password=" + password + ", perfils=" + perfils + "]";
	}

}
